### ISSUE TITLE
Console Errors!

### ISSUE THREAD

**Issue by BboyZeroOne** [Indyuce/bounty-hunters#38] opened 2020-05-20 23:16 UTC
Console Error, please check.

Inactive Player console spam:
https://pastebin.com/ySTgDCCy

Kicks player upon joining server:
https://pastebin.com/0VxsUGiv

**Comment by Kosinkadink** [comment] 2020-06-02 05:34
Can confirm this error is also happening for me. Looks like the the issue is inside BountyInactivityRemoval.java on line 43. The event is defined as synchronous, but is being created in a Runnable (async). 

@Indyuce you can probs fix this by replacing that line with this:
`Bukkit.getScheduler().runTask(BountyHunters.getInstance(), () -> Bukkit.getPluginManager().callEvent(new BountyExpireEvent(bounty, null, bounty.getReward(), BountyExpireCause.INACTIVITY)));`

This should schedule the event to run synchronously from the Runnable. I haven't pulled the repo and tried building it, but this should pretty much be the whole fix.

Another solution is to instead define BountyExpireEvent an asynchrounous event, but that might also have some unintended scheduling side effects depending on what you plan to do with the BountyExpireEvent moving forwards. It could be what you want though, so I'd give it a google.

Quick link to the line mentioned:
https://github.com/Indyuce/bounty-hunters/blob/e92cbe375c330c61faee6dcdc482ab003562f83c/src/net/Indyuce/bountyhunters/api/BountyInactivityRemoval.java#L43

**Comment by LostAndDead** [comment] 2020-06-04 20:59
any idea when a fix will be pushed for this? (i get it on legacy btw)

**Comment by BboyZeroOne** [comment] 2020-06-04 21:01
@Indyuce We have two more users having the same issue

**Comment by Indyuce** [comment] 2020-07-04 15:34
Will be fixed in the next spigot build

**Closed as completed by Indyuce** 2020-07-04 15:34 UTC
Labels: bug
